packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": 5.85.5
  "@types/node": ^24.3.0
  eslint: ^9.34.0
  prettier: ^3.6.2
  typescript: ^5.9.2
  zod: ^3.25.67

catalogs:
  react19:
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3
    react: 19.2.2
    react-dom: 19.2.2

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - bigint-buffer
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - msgpackr-extract
  - secp256k1
  - sharp
  - unrs-resolver
  - utf-8-validate
