packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.34.0
  prettier: ^3.6.2
  typescript: ^5.9.2
  zod: ^3.25.67
  '@tanstack/react-query': ^5.85.5
  '@types/node': ^24.3.0

catalogs:
  react19:
    react: 19.1.1
    react-dom: 19.1.1
    '@types/react': ^19.1.11
    '@types/react-dom': ^19.1.7

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - msgpackr-extract
  - secp256k1
  - sharp
  - unrs-resolver
  - utf-8-validate
